name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        shell: pwsh
        run: |
          $isPre = "${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}"
          $args = @(
            'release', 'create', '${{ github.ref_name }}',
            'dist/*.exe', 'dist/*.exe.blockmap',
            '--title', '${{ github.ref_name }}',
            '--generate-notes'
          )
          if ($isPre -eq 'false') { $args += '--latest' }
          if ($isPre -eq 'true') { $args += '--prerelease' }
          & 'gh' $args
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
